config/routes.rb
Rails.application.routes.draw do
  resources :types
  resources :pokemons
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  has_and_belongs_to_many :types
end

app/models/type.rb
class Type < ApplicationRecord
  has_and_belongs_to_many :pokemons

  has_and_belongs_to_many :double_damage_from,
            class_name: "Type",
            join_table: :double_damage_from,
            foreign_key: :subject_id,
            association_foreign_key: :object_id

  has_and_belongs_to_many :double_damage_to,
            class_name: "Type",
            join_table: :double_damage_to,
            foreign_key: :subject_id,
            association_foreign_key: :object_id

  has_and_belongs_to_many :half_damage_from,
            class_name: "Type",
            join_table: :half_damage_from,
            foreign_key: :subject_id,
            association_foreign_key: :object_id

  has_and_belongs_to_many :half_damage_to,
            class_name: "Type",
            join_table: :half_damage_to,
            foreign_key: :subject_id,
            association_foreign_key: :object_id

  has_and_belongs_to_many :no_damage_from,
            class_name: "Type",
            join_table: :no_damage_from,
            foreign_key: :subject_id,
            association_foreign_key: :object_id

  has_and_belongs_to_many :no_damage_to,
            class_name: "Type",
            join_table: :no_damage_to,
            foreign_key: :subject_id,
            association_foreign_key: :object_id

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: %i[ show edit update destroy ]

  # GET /pokemons or /pokemons.json
  def index
    @pokemons = Pokemon.includes(:types).all
  end

  # GET /pokemons/1 or /pokemons/1.json
  def show
  end

  # GET /pokemons/new
  def new
    @pokemon = Pokemon.new
  end

  # GET /pokemons/1/edit
  def edit
  end

  # POST /pokemons or /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to @pokemon, notice: "Pokemon was successfully created." }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemons/1 or /pokemons/1.json
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to @pokemon, notice: "Pokemon was successfully updated." }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1 or /pokemons/1.json
  def destroy
    @pokemon.destroy
    respond_to do |format|
      format.html { redirect_to pokemons_url, notice: "Pokemon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pokemon_params
      params.require(:pokemon).permit(:base_experience, :forms_names, :height, :pokeapi_id, :is_default, :name, :order, :type_ids, :weight, :abilities_is_hidden, :abilities_slot, :abilities_names)
    end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: %i[ show edit update destroy ]

  # GET /types or /types.json
  def index
    damages = %i[double_damage_from double_damage_to half_damage_from
                 half_damage_to no_damage_from no_damage_to pokemons]
    @types = Type.includes(damages).all
  end

  # GET /types/1 or /types/1.json
  def show
    # assume that move_names is a valid ruby array code snippet
    @moves = begin
          eval(@type.moves_names)&.join(', ')
        rescue Exception
          ''
        end
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types or /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: "Type was successfully created." }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1 or /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: "Type was successfully updated." }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1 or /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: "Type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def type_params
      params.require(:type).permit(:pokeapi_id, :name, :generation_name, :double_damage_from_id, :double_damage_to_id, :half_damage_from_id, :half_damage_to_id, :no_damage_from_id, :no_damage_to_id, :generation_name, :move_damage_class_name, :moves_names, :pokemon_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Poke</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemons/_form.html.erb
<%= form_with(model: pokemon) do |form| %>
  <% if pokemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
        <% pokemon.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :base_experience %>
    <%= form.number_field :base_experience %>
  </div>

  <div class="field">
    <%= form.label :forms_names %>
    <%= form.text_field :forms_names %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.number_field :height %>
  </div>

  <div class="field">
    <%= form.label :pokeapi_id %>
    <%= form.number_field :pokeapi_id %>
  </div>

  <div class="field">
    <%= form.label :is_default %>
    <%= form.check_box :is_default %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :order %>
    <%= form.number_field :order %>
  </div>

  <div class="field">
    <%= form.label :types_id %>
    <%= form.text_field :types_id %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.number_field :weight %>
  </div>

  <div class="field">
    <%= form.label :abilities_is_hidden %>
    <%= form.check_box :abilities_is_hidden %>
  </div>

  <div class="field">
    <%= form.label :abilities_slot %>
    <%= form.number_field :abilities_slot %>
  </div>

  <div class="field">
    <%= form.label :abilities_names %>
    <%= form.text_field :abilities_names %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pokemons/edit.html.erb
<h1>Editing Pokemon</h1>

<%= render 'form', pokemon: @pokemon %>

<%= link_to 'Show', @pokemon %> |
<%= link_to 'Back', pokemons_path %>

app/views/pokemons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pokemons</h1>

<table>
  <thead>
    <tr>
      <th>Identifier</th>
      <th>Name</th>
      <th>Types</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pokemons.each do |pokemon| %>
      <tr>
        <td><%= pokemon.pokeapi_id %></td>
        <td><%= pokemon.name %></td>
        <td><%= pokemon.types.map{|type| type.name}.join(', ') %></td>
        <td><%= link_to 'Show', pokemon %></td>
        <td><%= link_to 'Edit', edit_pokemon_path(pokemon) %></td>
        <td><%= link_to 'Destroy', pokemon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pokemon', new_pokemon_path %>

app/views/pokemons/new.html.erb
<h1>New Pokemon</h1>

<%= render 'form', pokemon: @pokemon %>

<%= link_to 'Back', pokemons_path %>

app/views/pokemons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Base experience:</strong>
  <%= @pokemon.base_experience %>
</p>

<p>
  <strong>Forms names:</strong>
  <%= @pokemon.forms_names %>
</p>

<p>
  <strong>Height:</strong>
  <%= @pokemon.height %>
</p>

<p>
  <strong>Pokeapi:</strong>
  <%= @pokemon.pokeapi_id %>
</p>

<p>
  <strong>Is default:</strong>
  <%= @pokemon.is_default %>
</p>

<p>
  <strong>Name:</strong>
  <%= @pokemon.name %>
</p>

<p>
  <strong>Order:</strong>
  <%= @pokemon.order %>
</p>

<p>
  <strong>Types:</strong>
  <%= @pokemon.types.map{|type| type.name}.join(', ') %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @pokemon.weight %>
</p>

<p>
  <strong>Abilities is hidden:</strong>
  <%= @pokemon.abilities_is_hidden %>
</p>

<p>
  <strong>Abilities slot:</strong>
  <%= @pokemon.abilities_slot %>
</p>

<p>
  <strong>Abilities names:</strong>
  <%= @pokemon.abilities_names %>
</p>

<%= link_to 'Edit', edit_pokemon_path(@pokemon) %> |
<%= link_to 'Back', pokemons_path %>

app/views/types/_form.html.erb
<%= form_with(model: type) do |form| %>
  <% if type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
        <% type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pokeapi_id %>
    <%= form.number_field :pokeapi_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :generation_name %>
    <%= form.text_field :generation_name %>
  </div>

  <div class="field">
    <%= form.label :double_damage_from_id %>
    <%= form.text_field :double_damage_from_id %>
  </div>

  <div class="field">
    <%= form.label :double_damage_to_id %>
    <%= form.text_field :double_damage_to_id %>
  </div>

  <div class="field">
    <%= form.label :half_damage_from_id %>
    <%= form.text_field :half_damage_from_id %>
  </div>

  <div class="field">
    <%= form.label :half_damage_to_id %>
    <%= form.text_field :half_damage_to_id %>
  </div>

  <div class="field">
    <%= form.label :no_damage_from_id %>
    <%= form.text_field :no_damage_from_id %>
  </div>

  <div class="field">
    <%= form.label :no_damage_to_id %>
    <%= form.text_field :no_damage_to_id %>
  </div>

  <div class="field">
    <%= form.label :generation_name %>
    <%= form.text_field :generation_name %>
  </div>

  <div class="field">
    <%= form.label :move_damage_class_name %>
    <%= form.text_field :move_damage_class_name %>
  </div>

  <div class="field">
    <%= form.label :moves_names %>
    <%= form.text_field :moves_names %>
  </div>

  <div class="field">
    <%= form.label :pokemon_id %>
    <%= form.text_field :pokemon_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Types</h1>

<table>
  <thead>
    <tr>
      <th>Identifier</th>
      <th>Name</th>
      <th>Double damage from</th>
      <th>Double damage to</th>
      <th>Half damage from</th>
      <th>Half damage to</th>
      <th>No damage from</th>
      <th>No damage to</th>
      <th>Pokemon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td><%= type.pokeapi_id %></td>
        <td><%= type.name %></td>
        <td><%= type.double_damage_from.map{|ens| ens.name}.join(', ') %></td>
        <td><%= type.double_damage_to.map{|ens| ens.name}.join(', ') %></td>
        <td><%= type.half_damage_from.map{|ens| ens.name}.join(', ') %></td>
        <td><%= type.half_damage_to.map{|ens| ens.name}.join(', ') %></td>
        <td><%= type.no_damage_from.map{|ens| ens.name}.join(', ') %></td>
        <td><%= type.no_damage_to.map{|ens| ens.name}.join(', ') %></td>
        <td><%= type.pokemons.map{|ens| ens.name}.join(', ') %></td>
        <td><%= link_to 'Show', type %></td>
        <td><%= link_to 'Edit', edit_type_path(type) %></td>
        <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type', new_type_path %>

app/views/types/new.html.erb
<h1>New Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pokeapi:</strong>
  <%= @type.pokeapi_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @type.name %>
</p>

<p>
  <strong>Generation name:</strong>
  <%= @type.generation_name %>
</p>

<p>
  <strong>Double damage from:</strong>
  <%= @type.double_damage_from.map{|ens| ens.name}.join(', ') %>
</p>

<p>
  <strong>Double damage to:</strong>
  <%= @type.double_damage_to.map{|ens| ens.name}.join(', ') %>
</p>

<p>
  <strong>Half damage from:</strong>
  <%= @type.half_damage_from.map{|ens| ens.name}.join(', ') %>
</p>

<p>
  <strong>Half damage to:</strong>
  <%= @type.half_damage_to.map{|ens| ens.name}.join(', ') %>
</p>

<p>
  <strong>No damage from:</strong>
  <%= @type.no_damage_from.map{|ens| ens.name}.join(', ') %>
</p>

<p>
  <strong>No damage to:</strong>
  <%= @type.no_damage_to.map{|ens| ens.name}.join(', ') %>
</p>

<p>
  <strong>Generation name:</strong>
  <%= @type.generation_name %>
</p>

<p>
  <strong>Move damage class name:</strong>
  <%= @type.move_damage_class_name %>
</p>

<p>
  <strong>Moves names:</strong>
  <%= @moves %>
</p>

<p>
  <strong>Pokemon:</strong>
  <%= @type.pokemons.map{|ens| ens.name}.join(', ') %>
</p>

<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>